package com.store.qrcode.common

val REQUEST_CAMERA = 1
val REQUEST_GALLERY = 2
val DEFAULT_INDEX = -1
val UNSELECT_INDEX= -1
val VERSION = "0.0.1"
val LABEL_CLIPBOARD = "LABEL_CLIPBOARD"
val GALLERY_RESULT = "GALLERY_RESULT"
val DATA_STORE_NAME = "settings"
val HTTP = "http://"
val HTTPS = "https://"
val SHARE_FILE = "share_file"
val SHARED_PREFERENCE_LANGUAGE = "SHARED_PREFERENCE_LANGUAGE"
val LANGUAGE = "LANGUAGE"